apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
  namespace: staging
spec:
  selector:
    matchLabels:
      app: busybox
  replicas: 1
  template:
    metadata:
      labels:
        app: busybox
    spec:
      volumes:
      - name: the-secret-volume
        secret:
          secretName: the-secret
      containers:
      - name: test
        image: busybox:1.30
        volumeMounts:
        - name: the-secret-volume
          mountPath: "/secrets"
          readOnly: true
        command: ['/bin/sh']
        args:  ['-c', 'eval "$SCRIPT"']
        env:
        - name: FILE_PATH
          value: /secrets/secret-file.txt
        - name: SCRIPT
          value: |-
            while true; do
              sleep 1
              echo "The secret text is: $(cat $FILE_PATH)"
            done
